### ISSUE TITLE
Upload to Pypi

### ISSUE THREAD

**Issue by johanneskoester** [EGA-archive/ega-download-client#10]
Please consider uploading to Pypi.

**Comment by tk2** [comment]
Agreed on both counts. I believe Pypi is in progress @AlexanderVi can confirm.

**Comment by AlexanderVi** [comment]
yes, PyPi  is in progress - will be a part of upcoming TravisCI intergration

**Comment by AlexanderVi** [comment]
fixed by fc20ffe7ecfca61c0c47002879358894cc108d81
