### ISSUE TITLE
Failed to obtain IP address

### ISSUE THREAD

**Issue by GodloveD** [EGA-archive/ega-download-client#100]
I can install and use v3.3.0 without any issues, but when I install and try to use v3.4.0, I get the following:
```
$ pyega3 -t datasets
ERROR:root:Failed to obtain IP address
```
I don't really know where to begin trying to debug this error.  Thank you.

**Comment by malloryfreeberg** [comment]
Hi @GodloveD. If you are running pyega3 v3.4.0, you can find a debug log which was automatically generated in the directory where you ran the pyega3 command. It is named `pyega3_output.log`. This is a good place to start to investigate what the issue might be.

**Comment by GodloveD** [comment]
So the file `pyega3_output.log` is created, but it is empty.  If I add the `-d` flag to the above command for debugging output it still just prints the same error message and then doesn't do anything else.

**Comment by malloryfreeberg** [comment]
Hi @GodloveD. Thank you for confirming there is nothing written to the output log. We need to investigate further on our end and will schedule a fix for this issue in our internal ticketing system in the new year. In the meantime, I suggest rolling back to v3.3.0 since it works for you.

Have a wonderful holiday/new year break! 🎉

**Comment by GodloveD** [comment]
Hello @malloryfreeberg.  I'm just wondering if there is any progress on this issue.  I'm working with a scientist who is having trouble downloading a dataset and opened a  ticket with the EGA helpdesk.  Our contact there suggested we download the latest version of pyega3 and try that.  Unfortunately, 3.4.1 still produces the same error when I install it and try to query datasets.

**Comment by jingyu9603** [comment]
Hi @GodloveD . I had the same problem, and I wonder if you have solved it.

**Comment by pscepanovic** [comment]
Hi! Absolutely the same issue here. The problem arrises when I'm on VPN of my institution. Thanks.

**Comment by pscepanovic** [comment]
it seems that the EGA python library pyega3 uses a service to get the IP that is blocked by my institution. 

Changing it to another one allowed makes the client work:

Replace
endpoint = 'https://ipinfo.io/json'
with
endpoint = 'https://api.myip.com'
in pyega3.py (line 44) in the python module installation . 

Hope that helps.

**Comment by Lucyj7** [comment]
Do you need QUICK and reliable hacker service
contac
Henryclarkethicalhacker (at) gmail com, is the solution,

**Comment by BigBella001** [comment]
I saw this link in a blog, [Henryclarkethicalhacker @ gmail .com, after years of searching and decided to contact them when i had a case with my spouse i dont know how they did it but they did get me remote access to his Whatsapp, Facebook, everything including phone calls.
Text him, Whatsapp,+ 12622367526. ..

**Comment by MVesuviusC** [comment]
> it seems that the EGA python library pyega3 uses a service to get the IP that is blocked by my institution.
> 
> Changing it to another one allowed makes the client work:
> 
> Replace endpoint = 'https://ipinfo.io/json' with endpoint = 'https://api.myip.com' in pyega3.py (line 44) in the python module installation .
> 
> Hope that helps.

This seems to have worked for me, though I needed to edit .../pyega3/libs/utils.py at line 81 (https://github.com/EGA-archive/ega-download-client/blob/5ec6c4cd37cc67142285051bdbd725c824da1384/pyega3/libs/utils.py#L96)
