### ISSUE TITLE
504 server error, slice error, failed and retried attempt for 2 weeks

### ISSUE THREAD

**Issue by jasmine9764** [EGA-archive/ega-download-client#106]
Dear EGA,
We have tried downloading UKB data through pyega3 for more than 2 weeks but it appeared the same error as the figure below

![image](https://user-images.githubusercontent.com/68228917/113499192-92ea2580-9546-11eb-831e-a3ad4443bf40.png)

We have tried both desktop computer and Microsoft Azure. We have enough storage for the data.
The downloading speed of Azure showed 2 times faster than desktop. Some chromosome files have been successfully downloaded. However, failure of 6-8 files is repeatedly reported.

We have reported the issue to helpdesk #491913 but no response was received. Posting here to see if anyone facing same issues or advice is greatly appreciated.
It has affected our research procedure and I look forward to a solution.
Thank you!

**Comment by malloryfreeberg** [comment]
Hi @jasmine9764,

Thank you for reporting this issue. I can see that the EGA Helpdesk has been in touch with you regarding your ticket. This type of issue is usually transient, so if you are still experiencing this behavior, please continue corresponding with the EGA Helpdesk as they are best suited to provide further assistance. Thank you for using pyega3!
