### ISSUE TITLE
repeated failures to download genomic region (from Australia)

### ISSUE THREAD

**Issue by JocelynSP** [EGA-archive/ega-download-client#109]
**Downloading frequently fails** 

*Error message:  htsget.exceptions.RetryableIOError: 500 Server Error*

**Description of the bug**

Fetching a bam file for a specific genomic range (Mitochondrial genome) via htsget quite often crashes on the 6th failed transfer attempt. This also occurs for full file downloads, but this is not such an issue as other download methods are available such as aspera.
Command used is 
pyega3 -cf jocCRED.json fetch --reference-name MT  

I attach 3 example log files :
[slurm-1351941.log](https://github.com/EGA-archive/ega-download-client/files/6322117/slurm-1351941.log)
[slurm-1351483.log](https://github.com/EGA-archive/ega-download-client/files/6322119/slurm-1351483.log)
[slurm-1351451.log](https://github.com/EGA-archive/ega-download-client/files/6322120/slurm-1351451.log)

**Comment by JocelynSP** [comment]
I have had very supportive email conversations with your team regarding this, but I thought it helpful to other users to also log publicly as an issue

**Comment by CsabaHalmagyi** [comment]
The htsget service was restored when python client version 5.0.0 was released, please upgrade your client and try downloading the range again. Should you encounter any issues, please contact our helpdesk team directly at [helpdesk@ega-archive.org](mailto:helpdesk@ega-archive.org).
