### ISSUE TITLE
file_from and file_length type wrong for resume to work

### ISSUE THREAD

**Issue by FlyPythons** [EGA-archive/ega-download-client#139]
With the latest version on github, the file_from and file_length are str type in file 'libs/data_file.py' and cause comparison fails in Python 3.7.7.

Should probably change `if (file_from, file_length) in [(param[1], param[2]) for param in params]:` to `if (int(file_from), int(file_length)) in [(param[1], param[2]) for param in params]:`

**Comment by malloryfreeberg** [comment]
@FlyPythons - Thank you for reporting this! We will ensure this is addressed before the next version release.
