### ISSUE TITLE
Invalid Username, Password, or Secret Key

### ISSUE THREAD

**Issue by mdbarnesUCSD** [EGA-archive/ega-download-client#141]
**Issue:**
Unable to connect to pyEGA3 download server with credentials. Previously have used pyEGA3 to download data with success, but recently went to download more data and ran into an error that states the following:

`Invalid username, password or secret key - please check and retry. If problem persists contact helpdesk on helpdesk@ega-archive.org`

Followed up test, by running the command for listing available datasets to the test account:
`pyega3 -d -t datasets`

This ends up producing the same error message of using an "invalid username, password, or secret key". I see that issue #136 experienced a similar bug that was resolved by waiting. I waited a day, and am still experiencing the issue.

This issue exists when running with pyEGA3 v3.4.1 as well as pyEGA3 v4.0.0 when using python v3.7.9 on Mac OS.

Please let me know if there is any additional information that I can provide. Thanks!

**Comment by malloryfreeberg** [comment]
Hi @mdbarnesUCSD . Thank you for reporting this issue, which was affecting all our users but has now been resolved. In the future, please email the EGA Helpdesk at helpdesk@ega-archive.org (as indicated in the error message) with this issue and attach the output log produced by pyega3 (pyega3_output.log). The EGA Helpdesk team can then provide further assistance. Thank you!
