### ISSUE TITLE
issue: “Invalid Username, Password, or Secret Key”

### ISSUE THREAD

**Issue by toddey** [EGA-archive/ega-download-client#144]
Hi, 

   I'm sorry to bother you,  I previously have used pyEGA3 to download data successfully, but recently went to download more data and ran into an error that states the following:

     "Invalid username, password or secret key - please check and retry."

Then I ran the command for listing available datasets to the test account: pyega3 -d -t datasets
I got the same error message.And I wonder what's the problem with the my pyEGA3 and what I can do?

[pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/8113605/pyega3_output.log)

**Comment by malloryfreeberg** [comment]
Hi @toddey. Thank you for reporting this issue. Download via pyega3 is currently down, and we are working as hard as possible to resolve the issue. We have put up a [banner on the EGA website](https://ega-archive.org/) about the outage. When this banner is removed, normal download services will be resumed. Thank you for patience and understanding!
