### ISSUE TITLE
HTTPError: 500 Server Error

### ISSUE THREAD

**Issue by jtk622** [EGA-archive/ega-download-client#15]
I get the error below when I try to view the files in the dataset. It shows authentication success. Then it throws up the error after a few minutes. Is this related  to the database server issue or something else?

jtk@DESKTOP-JU2HIS0:~/ega-download-client$ python3 pyega3/pyega3.py -cf CREDENTIALS_FILE.json files EGAD000XXXXXX
EGA python client version 3.0.19
Authentication success for user 'jtk622@xxx.edu'
Traceback (most recent call last):
  File "pyega3/pyega3.py", line 367, in <module>
    main()
  File "pyega3/pyega3.py", line 353, in main
    reply = api_list_files_in_dataset(token, args.identifier)
  File "pyega3/pyega3.py", line 95, in api_list_files_in_dataset
    r.raise_for_status()
  File "/home/jtk/miniconda3/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/metadata/datasets/EGAD0000XXXXX/files

**Comment by AlexanderSenf** [comment]
Unfortunately this is related to an issue resulting from routing maintenance work carried out at our data centre. As a result several of the servers required to run this service currently not responding. I will update and close this issue when this has been addressed; most likely later today.

**Comment by AlexanderSenf** [comment]
It looks like the data center is up and running again, the API should now be available again. Please let us know if you experience any other problems.

**Comment by ATpoint** [comment]
Same error here. Can you confirm that this is a temporary problem?

**Comment by pphector** [comment]
This issue is recurrent. I don't know what can be done to fix it, but it is extremely common and I wish there was a way to address it without having to open a ticket with the EGA helpdesk every time.

**Comment by biocoreexpert** [comment]
having this error today:



pyEGA3 - EGA python client version 3.0.33 (https://github.com/EGA-archive/ega-download-client)
Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly

[2019-05-06 20:45:53 +0200] Authentication success for user 'xxxx@xxxx.no'
Traceback (most recent call last):
  File "/local/home/robinm/software2/ega-download-client/pyega3/pyega3.py", line 474, in <module>
    main()
  File "/local/home/robinm/software2/ega-download-client/pyega3/pyega3.py", line 467, in main
    file_name, file_size, check_sum = get_file_name_size_md5( token, args.identifier )            
  File "/local/home/robinm/software2/ega-download-client/pyega3/pyega3.py", line 147, in get_file_name_size_md5
    r.raise_for_status()
  File "/local/home/robinm/miniconda2/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/metadata/files/EGAF000

**Comment by AlexanderVi** [comment]
Please contact EGA helpdesk at **helpdesk@ega-archive.org** regarding internal server errors (500 Server Error) as they are not related to the python download client (pyEga3)
