### ISSUE TITLE
Exit code 0 but "Could not communicate with the EGA repository because of an error on the server"

### ISSUE THREAD

**Issue by stsergbg** [EGA-archive/ega-download-client#157]
**Could not communicate with the EGA repository because of an error on the server.**

Even though pyega3 does not download the specified file and fails with `Could not communicate with the EGA repository because of an error on the server.`, it does not do any (visible) retries and returns exit code 0.

**Used versions** (please complete the following information)
 - Operating System version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*Linux 30-Ubuntu SMP*
 - Python version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*3.9.7*
 - PyEGA3 version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*4.0.3*

**To Reproduce**

Downloading `EGAF00001405643` (the actual file id is not very important)
```pyega3 -c 30 -cf .ega-creds fetch EGAF00001405643 --max-retries 50 --output-dir /tmp/output_directory```

**Observed behaviour**

If the server cannot be reached on the first try, exception is raised:
`(error detail: 500 Server Error: for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00001405643)
Could not communicate with the EGA repository because of an error on the server.`
Also exit code 0 is returned

**Expected behaviour**

The program did not do any retries (even though 50 were specified) which I expected (retries do happen if the download was initiated). Also since the download is not finished, I expected non-zero exit code.

**Comment by gh-cweiss** [comment]
We are also experiencing this same set of errors.
`Could not communicate with the EGA repository because of an error on the server.`

**Comment by Beiusxzw** [comment]
Still I am suffering from errors of the EGA server for several months.
```
  File "/u/local/apps/python/3.9.6/gcc-4.8.5/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/u/local/apps/python/3.9.6/gcc-4.8.5/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/home/w/wanluliu/.local/lib/python3.9/site-packages/pyega3/libs/data_file.py", line 173, in download_file_slice_
    return self.download_file_slice(*args)
  File "/u/home/w/wanluliu/.local/lib/python3.9/site-packages/pyega3/libs/data_file.py", line 200, in download_file_slice
    with self.data_client.get_stream(path,
  File "/u/local/apps/python/3.9.6/gcc-4.8.5/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/u/home/w/wanluliu/.local/lib/python3.9/site-packages/pyega3/libs/data_client.py", line 48, in get_stream
    r.raise_for_status()
  File "/u/local/apps/python/3.9.6/gcc-4.8.5/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00005284842?destinationFormat=plain
[2022-06-05 06:42:46 -0700] Could not communicate with the EGA repository because of an error on the server.
Please retry later, or contact helpdesk@ega-archive.org for assistance.
(error detail: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/files/EGAF00005284842?destinationFormat=plain)
```

**Comment by aaclan-ebi** [comment]
Hi @stsergbg, Thanks for filing the issue and bringing this to our attention, the fix on the exit failure code should now be in the latest version 4.0.4.

@gh-cweiss @peter-yufan-zeng  There was also a change to do retries on the following type of errors (those errors mentioned above) which wasn't there before:

```
(error detail: 500 Server Error: for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00001405643) Could not communicate with the EGA repository because of an error on the server.
```

```
[2022-06-07 13:32:46 -0400] Could not communicate with the EGA repository because of an error on the server. Please retry later, or contact helpdesk@ega-archive.org for assistance. (error detail: 500 Server Error: for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/datasets)
```

The retrying on requests could still reach a limit if the service is really loaded. But based on our monitoring for the past few weeks this hasn't been the case, @Beiusxzw May I know if you're using the previous latest version 4.0.3  when you encountered that stream file error. That version should already have better retrying on stream file errors. 

I would recommend using the latest version 4.0.4 to mitigate these HTTP 500 errors. We are still working on additional improvements to the underlying service to continue improving the overall experience.

**Comment by stsergbg** [comment]
@aaclan-ebi thank you for the fix! I will test the update shortly
