### ISSUE TITLE
Invalid username, password or secret key 

### ISSUE THREAD

**Issue by hw538** [EGA-archive/ega-download-client#162]
Hello EGA team!

This error of "Invalid username, password or secret key " occurred during the data download process, i.e., in the beginning, there weren’t such errors (so my username and password is no problem), and data was being downloaded, and then suddenly this error happened and the downloading was interrupted.

I have tried many times and it still doesn’t work.
Would you have any advice?

![image](https://user-images.githubusercontent.com/15274940/177292363-614d1068-bce5-493e-a622-f014fea07b75.png)

**Comment by yulicarp** [comment]
same error

**Comment by nicoleversetwo** [comment]
Getting the same error, despite successful downloads in the last few weeks

**Comment by hw538** [comment]
Folks, it starts to work when I retried again today.

**Comment by tischfis** [comment]
still same error and help desk is not addressing

**Comment by BinghuaLi** [comment]
As the help desk mentioned "Please note, it can take up to four hours for the dataset(s) to become available for download through the API", this error is might because the account is not ready yet. It seems that the content of the error is not matched correctly. I waited overnight, and the error was solved.

**Comment by tischfis** [comment]
I've waited weeks.

**Comment by nicoleversetwo** [comment]
the main EGA website now reads "Due to staff annual leave, please expect a delay in response time to your helpdesk queries. We will answer as soon as we can, but in the interim we kindly ask you to refrain from creating duplicate tickets for the same issue. - Thanks EGA team"    .... doesn't look like anything will be resolved soon

**Comment by malloryfreeberg** [comment]
Hi all. I’m sorry you are experiencing this issue, and thank you for reporting it. We are aware of the instability of the service at the moment and are actively working to solve the underlying intermittent issues. If you continue to experience download issues, the best place to get assistance is by emailing the EGA Helpdesk (helpdesk@ega-archive.org) and attaching the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance and updates on a fix. Thank you in advance for your patience while we work to resolve this!

**Comment by malloryfreeberg** [comment]
Thank you, all, for your patience while we worked on and released a new version of both [pyega3 (v5.0.0)](https://pypi.org/project/pyega3/) and the underlying API. Please update to the newest version of pyega3 (you can find the instructions [here](https://github.com/EGA-archive/ega-download-client#installation-and-update)) to enjoy the new features, including a more stable service which results in a higher download success rate. You should also only receive the "Invalid username, password or secret key" error if indeed the wrong credentials are being used.

This GH issue will be closed, but if you continue to experience the same problem, feel free to re-open it. If you experience any other problems, please email the EGA Helpdesk at helpdesk@ega-archive.org and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. Thank you!

**Comment by Ashford-A** [comment]
I've been having this same issue trying to download a dataset I was given access to a few weeks ago. Any ideas?

**Comment by SuhasSrinivasan** [comment]
#228
