### ISSUE TITLE
ega-openid-connect-server returns 400 error on bad credentials

### ISSUE THREAD

**Issue by delocalizer** [EGA-archive/ega-download-client#166]
## Description
The auth server returns 400 code on bad credentials. But 400 means "invalid request" — that is, the request could not be understood by the server.

## Expected Behaviour
The auth server returns an error code that enables the client to work out what is wrong.

e.g. for invalid credentials:
401 Unauthorized

e.g. for valid credentials but no authorization on the requested resource:
403 Forbidden

## Actual Behaviour
A 400 status code is returned no matter what.

## Notes
I know this is an issue against the EGA server and not the download client but I can't seem to find a github repo for the server — if there is one and I've just missed it please let me know and I'll close this and reopen there.

**Comment by CsabaHalmagyi** [comment]
EGA uses an openid connect overlay, the responses can not be changed from there unfortunately.
