### ISSUE TITLE
Error while downloading the dataset

### ISSUE THREAD

**Issue by alkurowska** [EGA-archive/ega-download-client#167]
Hello,

I have been trying to fetch my file from a dataset, however I constantly get the following error:
Traceback (most recent call last):
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/bin/pyega3", line 8, in <module>
    sys.exit(main())
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/pyega3/pyega3.py", line 670, in main
    display_file_name, file_name, file_size, check_sum = get_file_name_size_md5(token, args.identifier)
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/pyega3/pyega3.py", line 250, in get_file_name_size_md5
    r.raise_for_status()
  File "/ibex/sw/csi/pyega3/3.4.1/el7.9_python3/miniconda3/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00004726996

I am also not able to list files in a dataset. The only thing that works is "pyega3 datasets".
Thank you for any advice.
Regards,
Aleksandra

**Comment by danarte** [comment]
Having the same issue.

**Comment by danarte** [comment]
I just updated from an old pyega 3.4.1 version to the new 4.0.5 and the download started. 
So perhaps try updating the tool.

Although I still can't view the files on the website for some reason.

**Comment by LuoPangpang** [comment]
--"I just updated from an old pyega 3.4.1 version to the new 4.0.5 and the download started." -- this doesn't seem to work for me, I have been using the v4.0.5 and the 500 error responses persists.

**Comment by malloryfreeberg** [comment]
Hi @LuoPangpang. I’m sorry you are experiencing this issue, but thank you for reporting it. As this is an issue related to your specific user account, if you are still experiencing this behavior, please email the EGA Helpdesk at helpdesk@ega-archive.org with this issue and attach the output log file produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. Thank you.

**Comment by malloryfreeberg** [comment]
Thank you, all, for your patience while we worked on and released a new version of both [pyega3 (v5.0.0)](https://pypi.org/project/pyega3/) and the underlying API. Please update to the newest version of pyega3 (you can find the instructions [here](https://github.com/EGA-archive/ega-download-client#installation-and-update)) to enjoy the new features, including a more stable service which results in a higher download success rate.

This GH issue will be closed, but if you continue to experience the same problem, feel free to re-open it. If you experience any other problems, please email the EGA Helpdesk at helpdesk@ega-archive.org and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance. Thank you!
