### ISSUE TITLE
User password security

### ISSUE THREAD

**Issue by RichardCain** [EGA-archive/ega-download-client#17]
Putting users' passwords in clear text in a config file seems insecure. It means that anyone sharing the computer can log in as the same user, and can see the password which is likely to have been reused, rendering other systems vulnerable to attack.
May I suggest that the username and password should be passed as input parameters instead?

Thanks

Rich Cain

**Comment by AlexanderVi** [comment]
Fixed in ff7d215 ( now specifying password in the config file is not mandatory )
