### ISSUE TITLE
Server stability is shockingly bad

### ISSUE THREAD

**Issue by Nusob888** [EGA-archive/ega-download-client#171]
Dear EGA team, 

I appreciate your efforts, but the EGA download client is not currently fit for purpose. 
I have spent 6 months trying to download a single dataset. If the servers are not down, it times out. There is also no way to resume a incomplete download based on the documentation. 

As of now, I can connect maybe 3 out of 30 attempts and the download speed is shocking, often crawling to a stop then failing. 

There is literally no other data repo that I have experienced that is this bad. SRA is excellent and ENA is great. 

Is there any possibility that you may fix the server issues in the near future?

**Comment by CsabaHalmagyi** [comment]
Dear @Nusob888,
 
Thank you for bringing this to our attention. I can confirm that the team is working hard to fix the underlying issues. In the meantime if you are still experiencing this behaviour, please email the EGA Helpdesk at helpdesk@ega-archive.org with this issue and attach the output log produced by pyega3 (pyega3_output.log). The Helpdesk team can then provide further assistance including alternate options to retrieve the files.

**Comment by malloryfreeberg** [comment]
Thank you @Nusob888 for your patience while we worked on and released a new version of both [pyega3 (v5.0.0)](https://pypi.org/project/pyega3/) and the underlying API. Please update to the newest version of pyega3 (you can find the instructions [here](https://github.com/EGA-archive/ega-download-client#installation-and-update)) to enjoy the new features, including a more stable service which results in a higher download success rate and much faster authentication and authorisation steps. 

Downloads will automatically resume from where they left off provided the download location and filenames are the same. Files are downloaded in "chunks" and each chunk is saved separately. So all completed chunks do not need to be re-downloaded, only partial chunks that haven't finished when the connection was reset will need to be re-downloaded. If this doesn't happen for you, then please get in touch with the EGA Helpdesk team and report this issue, including providing the pyega3_output.log file.

This GH issue will be closed, but we encourage you to reach out to the EGA Helpdesk at helpdesk@ega-archive.org for any future specific issues you are facing, as they are best placed to help diagnose and fix them. Feel free to leave any feature enhancement or requests here in the pyega3 GH repo:) Thank you!
