### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by datakid** [EGA-archive/ega-download-client#18]
[Documentation](https://ega-archive.org/download/downloader-quickguide-v3#displayFiles) states usage of the software is like

`python pyega3/pyega3.py -cf CREDENTIALS_FILE fetch EGAD00001000951 <output>`

I found that this format would cause errors. 

`python pyega3/pyega3.py -cf CREDENTIALS_FILE fetch EGAD00001000951`

Worked fine.

**Comment by AlexanderVi** [comment]
Actually the correct format is (assuming installation via Pip)
`pyega3 -cf CREDENTIALS_FILE fetch EGAD00001000951  --saveto <output_dir>`

You can omit --saveto.  
The following comand will save to current dir.
`pyega3 -cf CREDENTIALS_FILE fetch EGAD00001000951`

**Comment by AlexanderVi** [comment]
Please add Mauricio and reassign to him , so he can fix the docs on ega-archive.org portal

**Comment by omllobet** [comment]
Hi @AlexanderVi This was already done some time ago so closing the issue.
