### ISSUE TITLE
Complete download without downloading any file

### ISSUE THREAD

**Issue by FlyPythons** [EGA-archive/ega-download-client#181]
**Title of the bug**

*Complete download without downloading any file*

**Description of the bug**

When using the lastest version of pyega3 (5.0.0), i got the message "Complete download" without  any file downloaded.

The bug may be caused by the "unknown" file status returned by current API. To solve this, you can change the `status_ok` function in `utils.py` to 
```
def status_ok(status_string):
    if status_string == "available":
        return True
    elif status_string == "unknown": # API does not currently include file status
        return True
    else:
        return False
```

**Used versions** (please complete the following information)
 - Operating System version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*`centos7.6`*
 - Python version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*`3.7.0`*
 - PyEGA3 version: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *`EGA python client version 5.0.0`*

**Comment by FlyPythons** [comment]
@malloryfreeberg The command used is  `pyega3 -c 10 -cf u.cfg fetch EGAD00001000978 --output-dir ./EGAD00001000978`. 
I am sorry about not providing the ouput, which has been deleted.  Now, I have replaced the code in the local machine and sloved the problem.

**Comment by aaclan-ebi** [comment]
Hi @FlyPythons @CsabaHalmagyi @malloryfreeberg

The issue should now be fixed in the latest version of pyega3.
https://github.com/EGA-archive/ega-download-client/releases/tag/v5.0.1

**Comment by CsabaHalmagyi** [comment]
Thank you Alegria. Closing.
