### ISSUE TITLE
Error downloading data - md5 values do not match

### ISSUE THREAD

**Issue by ccruizm** [EGA-archive/ega-download-client#183]
Good day, 

I am trying to download data that I got access to, but I am having problems with it. Using either one or multiple (tested with 5 and 20) connections, it seems there is a problem matching the md5 (e.g., `Download process expected md5 value 'edcf0553290bb8b7821aad8ca1e00189' but got '02b4f76b9cc6ef4d556ccb61a36c5952'`)

I am attaching the log file. How can I solve that problem? I appreciate any help you can provide.
[pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/10278336/pyega3_output.log)

**Comment by YuanlongLiu** [comment]
I encountered the same error using either the latest version or the docker version, tried multiple times with different number of connections.

Besides, the downloading speed was very very slow, sometimes only several kb/s. With this speed I may need one month to download the data I applied for (1TB).

Sorry to criticise but there is really need to make it easier for data downloading

**Comment by ccruizm** [comment]
Any news on this, please? I need to download more than 4TB of data, and with this issue, I have not been able to download any.

**Comment by bioruffo** [comment]
I've been trying to download a dataset, but so far, out of 148 checksums, 136 didn't match, causing those files to be discarded. Only 12 files were OK.  This  is unfortunate not only for the waste of time, but for bandwith usage on the server side, since download speeds are very low and each file was 3-5 GB.

**Comment by aaclan-ebi** [comment]
Hi @ccruizm @YuanlongLiu @bioruffo, there were issues in the new data API (which the pyega3 client is using for version 5.0.0 and above) just before the Christmas holidays and we needed to redeploy the service. After this, we noticed fewer errors on our logs so hopefully recent downloads should be fine, do you still encounter issues recently? The md5 error can still happen but it shouldn’t be as frequent as what happened to @bioruffo’s downloading.

@YuanlongLiu @bioruffo could you send me the dataset accession you’re trying to download? It would also be helpful if you could also send the pyega3 logs if you still have them. Meanwhile, I’ll check the logs from  @ccruizm. @ccruizm if you have recent logs that would also be helpful. 

Apologies for the inconvenience and thanks a lot for your patience!

**Comment by bioruffo** [comment]
Dear @aaclan-ebi ,
thank you heartily for your reply on this issue.
The dataset I'm downloading is EGAD00001006335.
I'm afraid I've deleted the log, as I've switched to downloading several files in parallel with one connection each, and I wanted to see how it performed without the records of the old log. Apologies, in case the issue arises again, I'll make sure to keep the logfile.

**Comment by YuanlongLiu** [comment]
Dear @aaclan-ebi, the dataset I am downloading are EGAD00001003257 and EGAD00001003258
I tried again today and still got the error. Plea
[pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/10351568/pyega3_output.log)
se see the attached log file

**Comment by bioruffo** [comment]
Apparently I can replicate the md5sum error consistently also by using smaller files available to the test account credentials.  

E.g., by using the following command (chunk size reduced to replicate big files' splitting into chunks):  
`pyega3 -d -cf credential.json -ms 3000000 fetch EGAF00007462314`  
The end result is:  
`Exception: Download process expected md5 value 'b2a36fc7043e807ad111c567120611bf' but got 'c6c36c44c620a29c1c4515552b9b6fab'`  
On multiple attempts, I get the same md5sum, so the slices appear to be downloaded in a consistent manner; but the complete file just doesn't match the expected value.  
[chunk3M_pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/10353237/chunk3M_pyega3_output.log)

Downloading it using the default chunk size, so in just one temporary file, also doesn't help,  
`pyega3 -d -cf credential.json fetch EGAF00007462314`  
Results in,  
`Download process expected md5 value 'b2a36fc7043e807ad111c567120611bf' but got '2cfcba4455657aa636c9057af89a9d02'`  
[pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/10353238/pyega3_output.log)

**Comment by bioruffo** [comment]
Adding more data:  
`pyega3 -d -t fetch EGAF00007462309`  
Resulted first in a successful download, then on a second attempt I got initially a slice error, and then a md5sum error on the first retry.  

[EGAF00007462309_pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/10353837/EGAF00007462309_pyega3_output.log)

**Comment by aaclan-ebi** [comment]
Hi @YuanlongLiu , @bioruffo 
Thanks so much for providing me with these details. They're very helpful. 

I believe there are 2 different issues here that need resolving based on the logs provided: 
1. **connection errors** (from @YuanlongLiu logs) - we're already working on improving the handling of requests to avoid this.
2. **md5 mismatch errors** (from @bioruffo @ccruizm logs)  I'm able to replicate the md5 mismatch issue consistently for the test file EGAF00007462314 but not for EGAF00007462309. I believe the issue only affects some data, and may be a data issue/decryption issue but unfortunately I couldn't pinpoint the issue yet. It's very interesting that it gets different checksums for different slice size. @bioruffo on your attempts to downloadthe 148 files, do the 136 consistently fail as well?
I will continue investigating and will post here as soon as I have significant updates.

**Comment by bioruffo** [comment]
Dear @aaclan-ebi ,
unfortunately as I was mentioning earlier, I don't have that logfile anymore, but I've restarted dowloading the files in the same way now, so I'll be able to provide a new one.
About files that failed more than once - I don't think there'd be information about repeated attempts in the logfile, because the dataset comprises more than 200 files, so the client hadn't technically made a full run yet.
Hopefully I'll send you fresh data in the following days (it takes some days to dowload a good amount of files).

**Comment by aaclan-ebi** [comment]
Hi, @ccruizm @bioruffo we've got a potential fix for the md5 mismatch issue but we would still like to test further as this affects the decryption of all files. Will hopefully be able to deploy this fix by early next week at the latest. A workaround and temporary solution to the md5 mismatch issue, for now, is to use the previous version of the client to use the older version of the API, `pip install pyega3==4.0.5`.

**Comment by aaclan-ebi** [comment]
Hi, @ccruizm @bioruffo the fix to the md5 mismatch issue is now deployed. There are no changes in the pyega3 client, only in our backend service. So, the latest version of pyega3 (5.0.1) should work. That issue only affects some files when a certain condition is met and we believe we fixed that. Thanks so much for providing the logs and details, we are able to replicate and fix the issue. Will keep this GH issue open for a few days for any further issues.

@YuanlongLiu  Regarding the connection errors, we may have a heavy load at times, and we can only advise to keep doing retries for now. I would scope this out of this GH issue but please be assured we're aware of and also working on it.

**Comment by CsabaHalmagyi** [comment]
Thank you for the update Alegria. Closing.
