### ISSUE TITLE
Issue with Dataset Visibility in PyEGA3

### ISSUE THREAD

**Issue by zhaowsong** [EGA-archive/ega-download-client#215]
Dear Sir/Madam,

We recently gained access to a database; however, we've encountered an issue. When attempting to download the data using the command 'pyega3 -cf credential_file.json datasets,' the dataset does not appear. We have waited for several days, but the problem persists. Is there a solution to this issue?

<img width="764" alt="image" src="https://github.com/EGA-archive/ega-download-client/assets/116059475/d9116dfa-64cb-46cd-b1fe-fb8029a6e0da">
（we have for datasets approved but show three）
Best regards
zhao

**Comment by CsabaHalmagyi** [comment]
Dear @zhaowsong 
Thank you contacting us. Permission related issues are dealt with our helpdesk team, please contact them directly at [helpdesk@ega-archive.org](mailto:helpdesk@ega-archive.org).
Closing this issue, as this is not for the attention of the dev team.
