### ISSUE TITLE
Function not implemented

### ISSUE THREAD

**Issue by hmkim** [EGA-archive/ega-download-client#217]
**Function not implemente**

 `pyega3 fetch`

**Description of the bug**

With S3 mount point, I could not use the pyega3 for downloading a data from EGA. 

**Used versions** (please complete the following information)
 - Operating System version: Amazon Linux 2023
 - Python version: Python 3.12.0
 - PyEGA3 version: 5.1.0

**To Reproduce**

Steps to reproduce the behaviour that led you to the bug.

*e.g.:*
1. Trying to download BAM file `EGAF00001775036`.
```
mount-s3 --allow-other --allow-delete --dir-mode 0777 <AWS S3 Bucket name> ~/mnt
cd ~/mnt
 pyega3 fetch EGAF00001775036
```

I keep getting errors.

[pyega3_output.log](https://github.com/EGA-archive/ega-download-client/files/13595971/pyega3_output.log)

I suspect this is due to a limitation in the behavior of locally mounted S3.
https://github.com/awslabs/mountpoint-s3/blob/main/doc/SEMANTICS.md#writes

**Comment by CsabaHalmagyi** [comment]
Using the python client with S3 has not been tested and currently we do not provide support for this. I added this as a feature request for the project.
