### ISSUE TITLE
GNU GPL code taken without attribution

### ISSUE THREAD

**Issue by jblachly** [EGA-archive/ega-download-client#23]
Note that this appears to be a straight up copy, with updates, of my repository:

https://github.com/blachlylab/pyega/

Please also note that the pyega license is GNU GPL, which requires attribution.

**Comment by tk2** [comment]
Hi James - I have emailed you about this issue. Have you seen it yet?

**Comment by AlexanderVi** [comment]
Hi James,
We've added attribution to pyEGA : https://github.com/EGA-archive/ega-download-client/commit/b801d7176ba7f958fd19c5d41842b37fb5ad58e7

**Comment by AlexanderSenf** [comment]
Closed after updating attributions.
