### ISSUE TITLE
Positional significance of CLI arguments is unexpected

### ISSUE THREAD

**Issue by SuhasSrinivasan** [EGA-archive/ega-download-client#233]
Dear EGA Team,

It is not clear why **optional** arguments have a position preference, which are followed by **positional** arguments and `(datasets,files,fetch)` can in turn be followed by more arguments.

**Requested enhancement:**
1. Please change positional arguments `(datasets,files,fetch)` to mandatory arguments 
2. Please provide `--` prefix for `(datasets,files,fetch)` so that users no longer have to guess the position of optional and mandatory arguments.

This does not work
```
$ pyega3 -cf ./ega_cred.json fetch EGAD00001005039 -c 4 --output-dir .
usage: pyega3 [-h] [-d] [-cf CONFIG_FILE] [-sf SERVER_FILE] [-c CONNECTIONS] [-t] [-ms MAX_SLICE_SIZE] [-j] [-v] {datasets,files,fetch} ...
pyega3: error: unrecognized arguments: -c 4

$ pyega3 -cf ./ega_cred.json fetch EGAD00001005039 --connections 4 --output-dir .
usage: pyega3 [-h] [-d] [-cf CONFIG_FILE] [-sf SERVER_FILE] [-c CONNECTIONS] [-t] [-ms MAX_SLICE_SIZE] [-j] [-v] {datasets,files,fetch} ...
pyega3: error: unrecognized arguments: --connections 4
```

While this works
```
$ pyega3  -c 4 -cf ./ega_cred.json fetch EGAD00001005039 --output-dir .
```
   
`--output-dir` is an optional argument, however it does not matter if it has to appear before `fetch` and it is fine to appear after `fetch`.   
   
The examples listed in README.md have `fetch` appearing prior to `-cf`, so it is not clear where `fetch`, `-cf` and other arguments are ok to be placed versus not.
```
pyega3 fetch -cf </Path/To/CREDENTIALS_FILE> --reference-name 1 --format BAM --output-dir </Path/To/OutputDirectory> EGAF<NUM>

pyega3 fetch -cf </Path/To/CREDENTIALS_FILE> --start 0 --end 1000000 --reference-name 1 --format BAM --output-dir </Path/To/OutputDirectory> EGAF<NUM>

```

**Comment by CsabaHalmagyi** [comment]
Dear @SuhasSrinivasan 
Thank you for raising this. The CLI argument order is documented in the readme and modifying this is not currently on the technical roadmap.
