### ISSUE TITLE
Guidelines for performance optimization

### ISSUE THREAD

**Issue by ATpoint** [EGA-archive/ega-download-client#27]
Could you provide some guidelines on how to most efficiently use the client `pyega3`?
Currently, while downloading a cohort of WGS data (EGAD00001002123), I experience slow download rates of about 2-4Mb/sec even dropping when using the `--connections` argument with 2-16 connections. pyega3 is being run from our CentOS HPC cluster and I/O is not an issue as downloads via `prefetch` from NCBI or `aspera` from ENA show rates of up to several tens of Mb/s even when running multiple jobs in parallel. Any advice on this, or a possibility to use Aspera to fetch the files?

Edit: I also receive plenty of error messages, below: (`pyega3 -cf creds.json fetch EGAD00001002123`).
Am I doing something wrong? I would greatly appreciate your comments.

best wishes, Alex

```
File Id: 'EGAF00001084045'(98445929616 bytes).
Download starting [using 16 connection(s)]...
401 Client Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001084045?destinationFormat=plain
401 Client Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001084045?destinationFormat=plain
File Id: 'EGAF00001155625'(135275682540 bytes).
Download starting [using 16 connection(s)]...
401 Client Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001155625?destinationFormat=plain
retry attempt 1
File Id: 'EGAF00001155625'(135275682540 bytes).
Download starting [using 16 connection(s)]...
401 Client Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001155625?destinationFormat=plain
retry attempt 2
File Id: 'EGAF00001155625'(135275682540 bytes).
Download starting [using 16 connection(s)]...
401 Client Error:  for url: https://ega.ebi.ac.uk:8051/elixir/data/files/EGAF00001155625?destinationFormat=plain
retry attempt 3
File Id: 'EGAF00001155625'(135275682540 bytes).
```

**Comment by AlexanderVi** [comment]
Yes, the download speed for EGAD00001002123 is very low and unstable ( for me jumps all the time in the range 1-20 MB/s. Anand, could pls you take a look at the logs? ( I've tested another dataset for comparison  EGAD00001003338 and it gives stable ~50 MB/s )
The second issue related to the fact that auth token expires after 1 hour (which in turn results 401 error ). Probably need to fix that by re-obtaing the token berore each retry.

**Comment by ATpoint** [comment]
Thank you for the fast reply. Due to my impatience (sorry for that) the same request was also submitted to the EGA helpdesk (#311755), but discussing the issue here is probably better to aslo help others.

**Comment by anandmohan777** [comment]
@ATpoint The output you have pasted in the first and last comment are different kind of errors. Could you pls explain your actual problem?

**Comment by ATpoint** [comment]
Update: Today, the connection for EGAD00001002123 is stable and download goes smoothly at 70Mb/s. The issues from the top level question that were confirmed by AlexanderVi seem to be no longer present.
