### ISSUE TITLE
Write md5 of verified files locally - prevent re-verification

### ISSUE THREAD

**Issue by keiranmraine** [EGA-archive/ega-download-client#28]
When a dataset fails part way through and is subsequently resumed every file has the MD5 verified.

Currently the MD5 is not written to the local file system.  The presence of the file locally could be used to indicate that a files has previously been verified as correct so that this isn't repeated each time a download is resumed.

Having the MD5 in a co-located file is additionally useful to the end-user should they need to move data at some point.

If a user wanted to re-verify all files a flag could be provided to force a recheck.

**Comment by AlexanderVi** [comment]
fixed in 4c8fc26
