### ISSUE TITLE
Are connections and split files directly related?

### ISSUE THREAD

**Issue by keiranmraine** [EGA-archive/ega-download-client#29]
The reason I was given to use many connections was not specifically for speed but to reduce the chance of a connection being interrupted when held open for a long time.  I have subsequently noticed that the number of segments a file is split into is correlated with the connection count.

Could the split files be migrated to be based on a `split-size`?  Parallel connections could round robin the list of splits.

This would allow more scope to prevent API oversubscription while still reducing problems due to dropped connections.

**Comment by AlexanderVi** [comment]
Yes, the number of chunks the file is being split into is correlated with the connection count (each connection downloads it's own chunk).  Given automatic retry and download resume already present I do not see advantage of migrating to "split-size"
