### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by SalvatoreRa** [EGA-archive/ega-download-client#33]
Hi, I am using my credentials which are working fine on the EGA website but is giving me back this error. I just downloaded and installed the client
C:\Users\Biogenera03> python pyega3/pyega3.py -cf CREDENTIALS_FILE datasets
pyEGA3 - EGA python client version 3.0.30 (https://github.com/EGA-archive/ega-download-client)
Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly

Authentication failure for user 'salvatore.raieli@biogenera.com'

I saved a file called CREDENTIALS_FILE in the folder pyega3 in my user directory.
I just substituited my credentials inside the fields

{
        "username": "my.email@domain",
        "password": "mypassword",
        "client_secret": "AMenuDLjVdVo4BSwi0QD54LL6NeVDEZRzEQUJ7hJOM3g4imDZBHHX0hNfKHPeQIGkskhtCmqAJtt_jm7EKq-rWw"
}

**Comment by AlexanderVi** [comment]
Could you please contact EGA helpdesk
