### ISSUE TITLE
Erroneous report of currupt md5

### ISSUE THREAD

**Issue by jdylan** [EGA-archive/ega-download-client#34]
A user reported 'corrupt md5' for a certain file. Looking at the logs on the API we see:
_[2019-03-14 07:23:37 -0400] [Errno 2] No such file or directory: '04-raw/XXXXXX.fastq.gz'_

So it looks like the client couldn't create the file specified in the "-saveto" command ("-saveto 04-raw/XXXXXX.fastq.gz"). And therefore it can;t calculate the MD5 of the nonexisting file.

Suggest a) a check on whether the directory exists ( or option to create it ) if -saveto is used, and b) extra error reporting such as 'file cannot be reconstructed' or 'downloaded file does not exist' for the cases where the write to disc or reconstruction of the file fails.

**Comment by AlexanderVi** [comment]
fixed in 58953f1
