### ISSUE TITLE
Self terminating download client

### ISSUE THREAD

**Issue by aritra90** [EGA-archive/ega-download-client#42]
Hi, 

While trying to download data sets it seems like there is authentication success but the download client is stopping after indicating authentication success. Not sure why. I could download two data sets  EGAD00000000001 and EGAD00000000002. The termination of download client starts from EGAD00000000003 onward. Although, we have access to the other data sets as well. 
Here is the snippet: 

`pyega3 -cf clientsec.json fetch EGAD00000000003`
`pyEGA3 - EGA python client version 3.0.33 (https://github.com/EGA-archive/ega-download-client)`
`Parts of this software are derived from pyEGA (https://github.com/blachlylab/pyega) by James Blachly`
`[2019-05-27 16:24:15 -0400] Authentication success for user 'XXXX'`

Please let me know what might be the reason.

**Comment by AlexanderVi** [comment]
There might be delay between authentication and the actual download - eventually you will see either an error or the download progress bar.
