### ISSUE TITLE
Download terminating with wrong MD5 sum

### ISSUE THREAD

**Issue by thommohr** [EGA-archive/ega-download-client#43]
Dear developers,

If the download is interrupted, they pyega3 client sometimes writes an md5 file with the wrong md5 sum. If the download is resumed, the md5 file is somehow not corrected, resulting in an error of the md5 sum. The client then retries the download but without deleting the md5 file. As a consequence, the retry also fails since the md5 sum is still wrong.

best,
Thomas

**Comment by AlexanderVi** [comment]
This has been fixed. Please upgrade to the latest version ( currently 3.0.38 ).
