### ISSUE TITLE
Human-Readable error logs

### ISSUE THREAD

**Issue by AlexanderSenf** [EGA-archive/ega-download-client#50]
The Python error log is useful, if you understand Python. If not it may be hard to see what exactly went wrong. 

Suggestion: Add human-readable error messages (in addition to the error log?) to inform users of the underlying error. This could be based on HTTP error codes, or from error messages returned for 500 errors.

**Comment by AlexanderVi** [comment]
I think the best way to achieve this is to display error messages returned from the server side.
