### ISSUE TITLE
Connection broken

### ISSUE THREAD

**Issue by vodkatad** [EGA-archive/ega-download-client#60]
Hello, I need to download some specific files from an EGA dataset...I started using the old java DemoClient (have some troubles with truncated files with it) then discovered about the python one, I have tried to download a single file for some hours now but the connection keeps getting broken:
[2019-11-19 17:09:34 +0100] File Id: 'EGAF00000908105'(15317127851 bytes).
[2019-11-19 17:09:34 +0100] Download starting [using 7 connection(s)]...
  1%|█▍                                                                                                                                                                        | 130M/15.3G [00:38<49:49, 5.08MB/s]
  1%|█▍                                                                                                                                                                     | 137M/15.3G [31:49<58:42:52, 71.8kB/s]
[2019-11-19 17:41:24 +0100] ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))

the connectivity where I am is good, when it works it downloads at ~2-3Mb/s - I have successfully uploaded a dataset on EGA in June... which parameters should  I play with to avoid having to retry by hand? Best number of connections? Is today an unlucky day? I have version 3.0.40 installed via conda.

**Comment by anandmohan777** [comment]
Oh, we had a connection problem that day. Pls update the pyega3 using command 'pip3 install update pyega3 -U' and then try the download.
