### ISSUE TITLE
Resume download after lost connection

### ISSUE THREAD

**Issue by nanakiksc** [EGA-archive/ega-download-client#67]
I am getting very frequent 500 (and 504) errors when `fetch`ing files.
After the error, the download starts all over again instead of resuming where it left off, which is very inefficient with such big files.

PS: I am using multiple (`-c 4`) connections.

**Comment by malloryfreeberg** [comment]
Hi @nanakiksc, 

Thank you for reporting this issue. We have made improvements to the download client that should ensure file downloads resume from where they left off as long as the output paths and filenames remain unchanged. 

If you are still experiencing this issue, please run your command(s) using the `-d` debug flag - which will generate a log - and email the log to the EGA Helpdesk at helpdesk@ega-archive.org for further assistance.
