### ISSUE TITLE
-r, -s and -e not working

### ISSUE THREAD

**Issue by nanakiksc** [EGA-archive/ega-download-client#68]
When using the options to `fetch` specific regions on files that are not indexed, I get either an incomplete file or no file at all.
I've been told that an index is required for these options to work, but the client should notify the user and exit in those cases, instead of silently crashing or giving abnormal output.

**Comment by malloryfreeberg** [comment]
Hi @nanakiksc,

Thank you for your comment. Can you clarify whether the behaviour you're observing is due to trying to fetch a file that you _don't_ expect to have an index (e.g. an Affymetrix CEL file) or a file that you _do_ expect to have an index (e.g. a CRAM or VCF file)? 

Thank you!

**Comment by nanakiksc** [comment]
These were BAM files, which can optionally have indices. I was told at EGA that the specific files I was trying to download did not have indices (it seems this depends on how they were uploaded the first time).
My suggestion was for the download client to notify the user in those cases, which would help differentiate an unsupported functionality (which is totally normal) from an actual error.

**Comment by malloryfreeberg** [comment]
Thank you for the clarification @nanakiksc. Indeed, a controlled exit in this situation with appropriate messaging would be ideal. We have scheduled this enhancement in our internal ticketing system, so I will close this issue now.

Thanks again for bringing this to our attention. Your feedback is very helpful and much appreciated :)
