### ISSUE TITLE
Gateway timeout/500 server error

### ISSUE THREAD

**Issue by elaplant** [EGA-archive/ega-download-client#69]
Hello, I'm trying to download files and it stopped working today. I have pyega3 installed on my windows laptop command line and on a linux system. On both systems I can list files contained within a dataset but when I go to download a file I get server errors.

When I try to download on the windows command line I get a server error and a Gateway Time-Out
![image](https://user-images.githubusercontent.com/53229123/74546515-45f55b00-4f10-11ea-8624-3421aee70b5a.png)

When I try on the Linux system I get the following error:
```
Traceback (most recent call last):
  File "/opt/python/3.6/bin/pyega3", line 11, in <module>
    load_entry_point('pyega3==3.0.44', 'console_scripts', 'pyega3')()
  File "/opt/python/3.6/lib/python3.6/site-packages/pyega3/pyega3.py", line 545, in main
    file_name, file_size, check_sum = get_file_name_size_md5( token, args.identifier )
  File "/opt/python/3.6/lib/python3.6/site-packages/pyega3/pyega3.py", line 201, in get_file_name_size_md5
    r.raise_for_status()
  File "/opt/python/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://ega.ebi.ac.uk:8052/elixir/data/metadata/files/EGAF00001745370

```

**Comment by pastaxingxin** [comment]
the same questions....

**Comment by malloryfreeberg** [comment]
Hi @elaplant and @pastaxingxin,

Thank you for reporting this issue. As this is a service issue, if you are still experiencing this behaviour, please run your command(s) using the -d debug flag - which will generate a log - and email the log to the EGA Helpdesk at helpdesk@ega-archive.org for further assistance.
