### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by eatsai** [EGA-archive/ega-download-client#7]
Hi,
I am able to use my credentials to decrypt files using EgaDemoClient.jar but somehow the same credentials result in a failure in this new ega download client. I've pasted my result below (actual username/email removed) Do you have a suggestion for me?

Thanks,
Ellen

$ python pyega3.py -d -cf ega_info.json 
EGA python client version 3.0.0
[debugging]
<Response [401]>
Request URL : https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
Response    : {
    "error": "invalid_client",
    "error_description": "Bad client credentials"
}
Authentication failure for user '[MY_EGA_LOGIN_EMAIL]'

**Comment by nurmians** [comment]
My credential work fine with EgaDemoClient.jar and at https://web2.ega-archive.org why has this issue been closed without any explanation?

EGA python client version 3.0.27
[debugging]
Password for '[myemail]':
[2018-11-18 20:51:45 +0200] Starting new HTTPS connection (1): ega.ebi.ac.uk
[2018-11-18 20:51:45 +0200] "POST /ega-openid-connect-server/token HTTP/1.1" 401 None
[2018-11-18 20:51:45 +0200] <Response [401]>

[2018-11-18 20:51:45 +0200] Request URL : https://ega.ebi.ac.uk:8443/ega-openid-connect-server/token
[2018-11-18 20:51:45 +0200] Response    :
 {
    "error": "invalid_client",
    "error_description": "Bad client credentials"
}
Authentication failure for user '[myemail]'
