### ISSUE TITLE
Use `"` instead of `'` for the exemplar JSON in the help text

### ISSUE THREAD

**Issue by IsmailM** [EGA-archive/ega-download-client#78]
The help text (`--help`) and the Readme show exemplar JSON for `-cf` and `-sf`...

This is quite helpful and useful in order to get started quickly.

However, this exemplar JSON uses single quotes instead of double quotes. As such, running pyega3 fails with the following message:

```bash
Invalid credential config JSON file
```

As such, please update the exemplar JSON to use `"` in the help text and readme.

PS. So far, pyEGA3 is a millions times easier to use than the old JAVA client or using `curl` - so thanks for this :)

**Comment by malloryfreeberg** [comment]
Hi @IsmailM,

Thank you very much for bringing this to our attention. We have scheduled this fix in our internal ticketing system, so I will close your issue now.

Glad to hear you are enjoying pyega3 :)

**Comment by malloryfreeberg** [comment]
Hi @IsmailM,

I'm pleased to let you know that this fix is now available in the newest release of pyEGA3! You can upgrade to the newest version - `pip3 install pyega3 --upgrade` or `conda update pyega3` - to see the fixed exemplar JSON.

Thanks again for using pyEGA3 and providing feedback to help us improve it :)
