### ISSUE TITLE
Option to skip md5 calculation at the end of a file download

### ISSUE THREAD

**Issue by ega-agent** [EGA-archive/ega-download-client#85]
Some downloads are completing to 100% but are timing out at the end of the download
Error seen is `("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))`
It is possible that the timeout is linked to the time needed to calculate the checksum of the downloaded file and run the check.

Would it be possible to include an optional flag in the next release that will disable the checksum verification so that we can separate issues with download from issues with data verification?

**Comment by jorizci** [comment]
No parameter will be added as that is intended to do not be skipeable. Further work pending on checking if both operations are coupled or not. Moved into internal operational issues.
